### PR TITLE
Feature Complete: Utulize Android accounts API, add multiple accounts support, show tags menu

### PR DESCRIPTION
**Pull request by kvj**
Grand idea: let application support multiple accounts with easy switch between them, like in google apps etc.

* [X] Add account authenticator classes
* [X] Refactor LoginActivity, create new Android account on success
* [X] Refactors stores in order to support multiple accounts
* [X] Add navigation drawer with current account info and account switcher
* [X] Replace current logout with account removal request
* [X] Show tags menu
* [ ] Sync contents according to system sync intents

Current status updated:
2017-02-10-123109_274x490_scrot 2017-02-10-123118_274x490_scrot

### CODE REVIEW

**Comment by mobitar** [comment]
Hmm I'm not so sure about this. This adds a lot of additional complexity, threatening longevity. Wouldn't the app be much simpler without this? Why would users need multiple accounts? The goal is to make sure the app is as easy to maintain as possible in the future. The more features, the more complexity, the harder it will be to maintain.

What would be the difference between this and the user just signing out and signing back in to another account manually?

**Comment by kvj** [comment]
@mobitar 

> Why would users need multiple accounts?
> What would be the difference between this and the user just signing out and signing back in to another account manually?

Since anyone can run standardfile server, most obvious example is work-related/personal notes stored separately.

There is no change from ordinal user point of view. Like now, you open app first time, enter the credentials and start using it.

**Comment by herbig** [comment]
It's not my app, but I kind of like the simplicity of it.  Adding multiple accounts for a small use case is a bit overkill, in my opinion.

Does this store user credentials on the device?

**Comment by mobitar** [comment]
> most obvious example is work-related/personal notes stored separately.

> Adding multiple accounts for a small use case is a bit overkill

Right I feel that is may be a use case for some people, but not the majority. Maybe only 1% will want multiple accounts. But it adds a lot of additional complexity. This will then require a lot of additional testing before every release. I think it may just be easier for the user to manually sign out then sign back in.

**Comment by deftelf** [comment]
Wow, that's great! But it is adding significant complexity at this point that I'm reluctant to bring into an unreleased app. We're currently very poor on tests and real-world use, and while I agree that this is something that the app may very well want in the future, it's going to create a testing burden now that we aren't ready for.

**Pull request closed without merging**
