### PR TITLE
Allow users to edit notes without being signed in

### PR DESCRIPTION
**Pull request by cr5315**

### CODE REVIEW

**Comment by deftelf** [comment]
Could you look in to why every line of some files is changed? Has the newline character changed or something? It's almost impossible to review because it shows 2500 line changes!

**Comment by deftelf** [comment]
Also, those tests in StarterActivity did have a purpose, and you've removed the lot of them without any replacements... If any change requires regression tests then it's one like this.

**Comment by mobitar** [comment]
@cr5315 any intention on fixing these issues?

**Comment by deftelf** [comment]
This is unreviewable. Sorry.

**Pull request closed without merging**
