### PR TITLE
Implement idling resource for ui test

### PR DESCRIPTION
**Pull request by nbau21**
@deftelf 
I've rebased this branch to master as well as added some stuff to make tests work on staging server (Idling Resource, using `launchActivity(intent)` on before each test, etc). Checkout commit e7316e09f0c4459821c2cc5f7888ecbad3454ece to see these changes.

I've tested this on a toy account I created on staging.

All tests pass now :) I'm not sure if they weren't on your end earlier. Feel free to checkout what you think is useful

### CODE REVIEW

**Comment by deftelf** [comment]
They were passing for me - though I was running on an emulator with animations turned off which might have been covering up some problems.

Thanks for this!

**Comment by deftelf** [comment]
So, now all the StarterActivityTests fail for me and the normal (non-test) login is broken. I'm not sure I feel this is an improvement...

**Comment by deftelf** [comment]
Not sure how this worked for you, but last 2 commits fixed it. If I have now broken it for you... we should probably discuss what's going on before making more changes.

**Comment by nbau21** [comment]
Whoops sorry about that.

**Comment by nbau21** [comment]
It looks like your fix commits are fine for me. I think it's mostly leftover cruft from when I was experimenting around the tests

**Pull request merged**
